require: 
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 2.7.3
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'tmp/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'app/admin/*.rb'
    - 'Guardfile'
    - 'config/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
