version: 2.1

commands:
  bundle_cache:
    steps:
      - restore_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  
jobs:
  lintering:
    docker:
      - image: cimg/ruby:2.7.6
    steps:
      - checkout
      - bundle_cache
      - run: bundle install 
      - run:
          name: rubocop
          command: bundle exec rubocop
      - run:
          name: brakeman
          command: bundle exec brakeman
      - run:
          name: fasterer
          command: bundle exec fasterer
          
  test:
    docker:
      - image: cimg/ruby:2.7.6
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: johnnyGsy
          POSTGRES_DB: rails_7_bookstore_test
          POSTGRES_PASSWORD: "password"
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      BOOK_STORE_DATABASE_PASSWORD: "password"
      RAILS_ENV: test
    steps:
      - checkout
      - bundle_cache
      - run: bundle install 
      - run:
          name: Install ImageMagick
          command: sudo apt-get install imagemagick
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: run specs
          command: bundle exec rspec
    parallelism: 4

workflows:
  lint_and_test:
    jobs:
      - lintering
      - test
