version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: cimg/ruby:2.7.6
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: johnnyGsy
          POSTGRES_DB: rails_7_bookstore_test
          POSTGRES_PASSWORD: "password"
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      BOOK_STORE_DATABASE_PASSWORD: "password"
      RAILS_ENV: test

caches:
  - &bundle_cache gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

commands:
  run_linters:
    description: command to start linters
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop
      - run:
          name: brakeman
          command: bundle exec brakeman -q
      - run:
          name: fasterer
          command: bundle exec fasterer
      - run:
          name: rails_best_practices
          command: bundle exec rails_best_practices
      - run:
          name: bundler-audit
          command: bundle exec bundler-audit --update


  run_specs:
    steps:
      - run:
          name: run specs
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                              --out /tmp/test-results/rspec.xml \
                              $TEST_FILES
  setup_environment:
    steps:
      - checkout
      - restore_cache:
          key: *bundle_cache
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: *bundle_cache
          paths:
            - vendor/bundle
      - run:
          name: Set up DB
          command: |
            bundle exec rake db:create
            bundle exec rails db:schema:load
<<<<<<< HEAD
=======

>>>>>>> fixing circleci
jobs:
  lintering:
    executor: default
    steps:
      - setup_environment
      - run_linters
  run_specs:
    executor: default
    steps:
      - setup_environment
      - run_specs
    parallelism: 4
  

workflows:
  build:
    jobs:
      - lintering
      - run_specs:
          requires:
            - lintering
            