
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  


development:
  <<: *default
  database: rails_7_bookstore_development
  host: localhost
  user: johnnyGsy
  password: password

 
test:
  <<: *default
  database: rails_7_bookstore_test
  host: localhost
  user: johnnyGsy
  password: password


production:
  <<: *default
  database: rails_7_bookstore_production