default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: johnnyGsy
  password: password
  

development:
  <<: *default
  database: rails_7_bookstore_development

 
test:
  <<: *default
  database: rails_7_bookstore_test


production:
  <<: *default
  database: rails_7_bookstore_production