
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: rails_7_bookstore_development

 
test:
  <<: *default
  database: rails_7_bookstore_test


production:
  <<: *default
  database: rails_7_bookstore_production